#!/usr/bin/env python3
"""Generate docs/config-reference.md from the config dataclasses.

The dataclass field docstrings are the single source of truth for config
documentation.  This script walks the ``ALGORITHMS`` registry, extracts every
field's name, type, default, and docstring, and writes a markdown reference.
A guard test (tests/test_config_reference.py) regenerates the document and
fails if the committed file is stale.

Usage (from the repo root)::

    python scripts/generate_config_reference.py          # write the file
    python scripts/generate_config_reference.py --check  # exit 1 if stale
"""
from __future__ import annotations

import argparse
import ast
import inspect
import sys
import textwrap
from dataclasses import fields, is_dataclass
from pathlib import Path

_ROOT = Path(__file__).resolve().parents[1]
if str(_ROOT) not in sys.path:
    sys.path.insert(0, str(_ROOT))

from core.base_config import RunConfig
from core.config_loader import ALGORITHMS, _import_algorithm

OUTPUT = _ROOT / "docs" / "config-reference.md"

# RunConfig fields populated by the algorithm at runtime — documented
# separately so nobody tries to set them in a YAML.
RUNTIME_FIELDS = {"batch_size", "minibatch_size", "num_iterations", "env_kwargs_id"}


def field_docstrings(cls: type) -> dict[str, str]:
    """Map field name -> docstring by pairing each annotated assignment in the
    class body with the string literal that immediately follows it."""
    tree = ast.parse(textwrap.dedent(inspect.getsource(cls)))
    class_body = tree.body[0].body
    docs: dict[str, str] = {}
    for stmt, nxt in zip(class_body, class_body[1:] + [None]):
        if not (isinstance(stmt, ast.AnnAssign) and isinstance(stmt.target, ast.Name)):
            continue
        if (
            isinstance(nxt, ast.Expr)
            and isinstance(nxt.value, ast.Constant)
            and isinstance(nxt.value.value, str)
        ):
            docs[stmt.target.id] = " ".join(nxt.value.value.split())
    return docs


def annotation_source(cls: type, name: str) -> str:
    """The field's type annotation exactly as written in the source."""
    tree = ast.parse(textwrap.dedent(inspect.getsource(cls)))
    for stmt in tree.body[0].body:
        if (
            isinstance(stmt, ast.AnnAssign)
            and isinstance(stmt.target, ast.Name)
            and stmt.target.id == name
        ):
            return ast.unparse(stmt.annotation)
    return "?"


def render_table(cls: type, *, skip: set[str] = frozenset(), only: set[str] | None = None) -> str:
    docs = field_docstrings(cls)
    instance = cls()
    lines = ["| Key | Type | Default | Description |", "|---|---|---|---|"]
    for f in fields(cls):
        if f.name in skip or (only is not None and f.name not in only):
            continue
        default = getattr(instance, f.name)
        if is_dataclass(default):  # nested sections get their own tables
            continue
        desc = docs.get(f.name, "")
        lines.append(
            f"| `{f.name}` | `{annotation_source(cls, f.name)}` "
            f"| `{default!r}` | {desc} |"
        )
    return "\n".join(lines)


def generate() -> str:
    parts = [
        "# Config Reference",
        "",
        "<!-- AUTO-GENERATED by scripts/generate_config_reference.py — do not edit by hand. -->",
        "",
        "Every key accepted in a YAML config (and by `--override`), with types,",
        "defaults, and the docstrings from the config dataclasses. A config only",
        "needs the keys that differ from the defaults; unknown keys abort at",
        "startup. Regenerate with:",
        "",
        "```bash",
        "python scripts/generate_config_reference.py",
        "```",
        "",
        "## Run-level keys",
        "",
        "Defined in `core/base_config.py::RunConfig`; shared by every algorithm.",
        "",
        render_table(RunConfig, skip=RUNTIME_FIELDS),
        "",
        "Runtime-computed fields (**do not set these** — the algorithm fills them",
        "in during `initialize()`; they appear in saved run `config.yml` files):",
        "",
        render_table(RunConfig, only=RUNTIME_FIELDS),
    ]

    run_level = {f.name for f in fields(RunConfig)}
    for algo_name in sorted(ALGORITHMS):
        ArgsClass, _ = _import_algorithm(algo_name)
        section_field = next(f for f in fields(ArgsClass) if f.name == algo_name)
        section_cls = section_field.default_factory  # type: ignore[union-attr]
        module = sys.modules[ArgsClass.__module__].__file__
        parts += [
            "",
            f"## `{algo_name}:` section",
            "",
            f"Defined in `{Path(module).relative_to(_ROOT)}::{section_cls.__name__}`. "
            f"Default `network`: `{ArgsClass().network}`.",
            "",
            render_table(section_cls),
        ]
        # Anything an Args adds beyond RunConfig + its own section
        # would otherwise be silently undocumented — refuse instead.
        extra = {
            f.name for f in fields(ArgsClass)
        } - run_level - {algo_name}
        if extra:
            raise SystemExit(
                f"{ArgsClass.__module__}.Args has undocumented top-level "
                f"fields {sorted(extra)}; teach the generator about them."
            )

    return "\n".join(parts) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="don't write; exit 1 if docs/config-reference.md is stale",
    )
    cli = parser.parse_args()

    content = generate()
    if cli.check:
        current = OUTPUT.read_text() if OUTPUT.exists() else ""
        if current != content:
            print(
                f"{OUTPUT.relative_to(_ROOT)} is stale — run: "
                "python scripts/generate_config_reference.py"
            )
            sys.exit(1)
        print(f"{OUTPUT.relative_to(_ROOT)} is up to date")
        return

    OUTPUT.write_text(content)
    print(f"wrote {OUTPUT.relative_to(_ROOT)}")


if __name__ == "__main__":
    main()
